NGINX_SITE_ENABLE_PATH="/usr/local/etc/nginx/site-enabled/"
CUR_DIR="`pwd`"
SERVER_NGINX_CONFIG_PATH="${CUR_DIR}/etc/nginx.conf"
HELLO_APP_RUN_SERVER_SCRIPT="${CUR_DIR}/init_scripts/bsd/hello_app"
ASK_APP_RUN_SERVER_SCRIPT="${CUR_DIR}/init_scripts/bsd/ask_app"
GUNICORN_APPS_PATH="/usr/local/etc/rc.d/"
