NGINX_SITE_ENABLE_PATH="/usr/local/nginx/conf/site-enabled/"
CUR_DIR="`pwd`"
SERVER_NGINX_CONFIG_PATH="${CUR_DIR}/etc/nginx.conf"
HELLO_APP_RUN_SERVER_SCRIPT="${CUR_DIR}/init_scripts/runit/hello_app"
ASK_APP_RUN_SERVER_SCRIPT="${CUR_DIR}/init_scripts/runit/ask_app"
