#!/bin/sh

. /etc/rc.d/ask_app/app_serv_conf.sh
. /etc/rc.subr

name=ask_app
rcvar=ask_app_enable

#set up command
command="${GUNICORN_EXEC}"

# start/stop commands
start_precmd="${name}_prestart"
stop_cmd="${name}_stop"

#set up pid file
pidfile="/var/run/${name}.pid"

GUNICORN_CONFIG_PATH="${GUNICORN_APP_PATH}/${name}"
APP=${APP_NAME}

ask_app_prestart()
{
   rc_flags="-c ${GUNICORN_CONFIG_PATH}/gunicorn.conf.py -p ${pidfile} ${APP} ${rc_flags}"
}

ask_app_stop()
{
    if [ -f $pidfile ]; then
        kill `cat $pidfile`
    else
        echo "ask_app is not running"
    fi
}

load_rc_config $name
run_rc_command "$1"
