#!/bin/sh

. /etc/rc.subr

name=hello_app
rcvar=hello_app_enable

#set up command
command="/usr/local/bin/gunicorn"

# start/stop commands
start_precmd="${name}_prestart"
stop_cmd="${name}_stop"

#set up pid file
pidfile="/var/run/${name}.pid"

GUNICORN_CONFIG_PATH="$2/etc"
APP="hello:app"

hello_app_prestart()
{
   mkdir /var/log/${name}-server
   rc_flags="-c ${GUNICORN_CONFIG_PATH}/gunicorn.conf.py -p ${pidfile} ${APP} ${rc_flags}"
}

hello_app_stop()
{
    if [ -f $pidfile ]; then
        kill `cat $pidfile`
        rm -rf "/var/log/${name}-server"
    else
        echo "hello_app is not running"
    fi
}

load_rc_config $name
run_rc_command "$1"
